version: "3"
services:
  
  ui:
   build:
      context: ./client
      dockerfile: dockerfile
   image: mern-ui
   ports:
    -  5173:5173
   container_name: mern-ui
   volumes:
    -  ./client/src:/usr/app/src
    -  ./client/public:/usr/app/public
   tty: true

  api:
   environment:
      - MONGO_URL=${MONGO_URL}
   build:
      context: ./api
      dockerfile: dockerfile
   image: mern-api
   ports:
     - 5000:5000
   container_name: mern-api
   volumes:
    - ./api/src:/usr/app/src

