# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      MONGO_URL: ${{ secrets.MONGO_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install server dependencies
        working-directory: api
        run: npm install

   #   - name: Build the server
    #    working-directory: api
      #  run: npm start

      - name: Run server tests
        working-directory: api
        run: npm test

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build the client
        working-directory: client
        run: npm run build

      - name: Run client tests
        working-directory: client
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker images
        run: docker-compose build

      - name: Tag Docker images
        run: |
          docker tag mern-ui malekghorbel/mern-ui:latest
          docker tag mern-api malekghorbel/mern-api:latest

      - name: Push Docker images
        run: |
          docker push malekghorbel/mern-ui:latest
          docker push malekghorbel/mern-api:latest

      - name: sonar
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: qube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}