# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install server dependencies
        working-directory: api
        run: npm install

      - name: Build the server
        working-directory: api
        run: npm run build

      - name: Run server tests
        working-directory: api
        run: npm test

      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build the client
        working-directory: client
        run: npm run build

      - name: Run client tests
        working-directory: client
        run: npm test
